[package]
name = "hyprland-vdm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
colorized = "1.0.0"
tokio = { version = "1.44.2", features = ["full"] }
